# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import crawler_pb2 as crawler__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in crawler_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class QueueServiceStub(object):
    """---- Queue Service (runs on Mac) ----
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetNextURL = channel.unary_unary(
                '/crawler.QueueService/GetNextURL',
                request_serializer=crawler__pb2.GetNextURLRequest.SerializeToString,
                response_deserializer=crawler__pb2.GetNextURLResponse.FromString,
                _registered_method=True)
        self.AddURLs = channel.unary_unary(
                '/crawler.QueueService/AddURLs',
                request_serializer=crawler__pb2.AddURLsRequest.SerializeToString,
                response_deserializer=crawler__pb2.AddURLsResponse.FromString,
                _registered_method=True)
        self.MarkVisited = channel.unary_unary(
                '/crawler.QueueService/MarkVisited',
                request_serializer=crawler__pb2.MarkVisitedRequest.SerializeToString,
                response_deserializer=crawler__pb2.MarkVisitedResponse.FromString,
                _registered_method=True)
        self.IsVisited = channel.unary_unary(
                '/crawler.QueueService/IsVisited',
                request_serializer=crawler__pb2.IsVisitedRequest.SerializeToString,
                response_deserializer=crawler__pb2.IsVisitedResponse.FromString,
                _registered_method=True)
        self.SeedURLs = channel.unary_unary(
                '/crawler.QueueService/SeedURLs',
                request_serializer=crawler__pb2.SeedURLsRequest.SerializeToString,
                response_deserializer=crawler__pb2.SeedURLsResponse.FromString,
                _registered_method=True)
        self.GetStats = channel.unary_unary(
                '/crawler.QueueService/GetStats',
                request_serializer=crawler__pb2.GetStatsRequest.SerializeToString,
                response_deserializer=crawler__pb2.GetStatsResponse.FromString,
                _registered_method=True)


class QueueServiceServicer(object):
    """---- Queue Service (runs on Mac) ----
    """

    def GetNextURL(self, request, context):
        """Get next URL to crawl (atomically dequeues)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddURLs(self, request, context):
        """Add discovered URLs to the queue
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def MarkVisited(self, request, context):
        """Mark a URL as visited (dedup)
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def IsVisited(self, request, context):
        """Check if a URL has been visited
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SeedURLs(self, request, context):
        """Seed initial URLs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStats(self, request, context):
        """Get stats
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_QueueServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetNextURL': grpc.unary_unary_rpc_method_handler(
                    servicer.GetNextURL,
                    request_deserializer=crawler__pb2.GetNextURLRequest.FromString,
                    response_serializer=crawler__pb2.GetNextURLResponse.SerializeToString,
            ),
            'AddURLs': grpc.unary_unary_rpc_method_handler(
                    servicer.AddURLs,
                    request_deserializer=crawler__pb2.AddURLsRequest.FromString,
                    response_serializer=crawler__pb2.AddURLsResponse.SerializeToString,
            ),
            'MarkVisited': grpc.unary_unary_rpc_method_handler(
                    servicer.MarkVisited,
                    request_deserializer=crawler__pb2.MarkVisitedRequest.FromString,
                    response_serializer=crawler__pb2.MarkVisitedResponse.SerializeToString,
            ),
            'IsVisited': grpc.unary_unary_rpc_method_handler(
                    servicer.IsVisited,
                    request_deserializer=crawler__pb2.IsVisitedRequest.FromString,
                    response_serializer=crawler__pb2.IsVisitedResponse.SerializeToString,
            ),
            'SeedURLs': grpc.unary_unary_rpc_method_handler(
                    servicer.SeedURLs,
                    request_deserializer=crawler__pb2.SeedURLsRequest.FromString,
                    response_serializer=crawler__pb2.SeedURLsResponse.SerializeToString,
            ),
            'GetStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStats,
                    request_deserializer=crawler__pb2.GetStatsRequest.FromString,
                    response_serializer=crawler__pb2.GetStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'crawler.QueueService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('crawler.QueueService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class QueueService(object):
    """---- Queue Service (runs on Mac) ----
    """

    @staticmethod
    def GetNextURL(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crawler.QueueService/GetNextURL',
            crawler__pb2.GetNextURLRequest.SerializeToString,
            crawler__pb2.GetNextURLResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddURLs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crawler.QueueService/AddURLs',
            crawler__pb2.AddURLsRequest.SerializeToString,
            crawler__pb2.AddURLsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def MarkVisited(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crawler.QueueService/MarkVisited',
            crawler__pb2.MarkVisitedRequest.SerializeToString,
            crawler__pb2.MarkVisitedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def IsVisited(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crawler.QueueService/IsVisited',
            crawler__pb2.IsVisitedRequest.SerializeToString,
            crawler__pb2.IsVisitedResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SeedURLs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crawler.QueueService/SeedURLs',
            crawler__pb2.SeedURLsRequest.SerializeToString,
            crawler__pb2.SeedURLsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crawler.QueueService/GetStats',
            crawler__pb2.GetStatsRequest.SerializeToString,
            crawler__pb2.GetStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class FileServiceStub(object):
    """---- File Service (runs on Windows) ----
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StoreLink = channel.unary_unary(
                '/crawler.FileService/StoreLink',
                request_serializer=crawler__pb2.StoreLinkRequest.SerializeToString,
                response_deserializer=crawler__pb2.StoreLinkResponse.FromString,
                _registered_method=True)
        self.StoreLinks = channel.unary_unary(
                '/crawler.FileService/StoreLinks',
                request_serializer=crawler__pb2.StoreLinksRequest.SerializeToString,
                response_deserializer=crawler__pb2.StoreLinksResponse.FromString,
                _registered_method=True)


class FileServiceServicer(object):
    """---- File Service (runs on Windows) ----
    """

    def StoreLink(self, request, context):
        """Store a crawled link to the text file
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StoreLinks(self, request, context):
        """Store multiple links
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FileServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StoreLink': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreLink,
                    request_deserializer=crawler__pb2.StoreLinkRequest.FromString,
                    response_serializer=crawler__pb2.StoreLinkResponse.SerializeToString,
            ),
            'StoreLinks': grpc.unary_unary_rpc_method_handler(
                    servicer.StoreLinks,
                    request_deserializer=crawler__pb2.StoreLinksRequest.FromString,
                    response_serializer=crawler__pb2.StoreLinksResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'crawler.FileService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('crawler.FileService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class FileService(object):
    """---- File Service (runs on Windows) ----
    """

    @staticmethod
    def StoreLink(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crawler.FileService/StoreLink',
            crawler__pb2.StoreLinkRequest.SerializeToString,
            crawler__pb2.StoreLinkResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StoreLinks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/crawler.FileService/StoreLinks',
            crawler__pb2.StoreLinksRequest.SerializeToString,
            crawler__pb2.StoreLinksResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
